[versions]
# libraries
json = "20250107"
junit = "5.14.1"
platformlauncher = "1.14.1"
mavenmodel = "3.9.10"
mockito = "5.18.0"
mockwebserver = "5.1.0"

# plugins
changelog = "2.5.0"
intelliJPlatform = "2.10.5"
kotlin = "2.2.21"
kover = "0.9.3"
qodana = "2025.2.2"

[libraries]
json = { group = "org.json", name = "json", version.ref = "json" }
junitjupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junitjupiterengine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junitplatformlauncher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "platformlauncher" }
mavenmodel = { group = "org.apache.maven", name = "maven-model", version.ref = "mavenmodel" }
mockitocore = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockitojunitjupiter = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "mockwebserver" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
